from collections import deque
queue = deque()
queue.append(1)
queue.append(2)
queue.append(3)
queue.append(4)
queue.append(5)
first_out = queue.popleft()
print(first_out)
queue.append(6)
queue.append(7)
second_out = queue.popleft()
print(second_out)
print(queue)
